// <auto-generated />
using System;
using AbbaXpress.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbbaXpress.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814182212_AddGastosOperativosTable")]
    partial class AddGastosOperativosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbbaXpress.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("TarifaAereo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TarifaMaritimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CodigoPais = "+505",
                            Direccion = "Managua, Reparto San Juan",
                            Email = "juan.perez@email.com",
                            FechaRegistro = new DateTime(2026, 8, 14, 18, 22, 11, 902, DateTimeKind.Utc).AddTicks(5041),
                            Nombre = "Juan Carlos Pérez",
                            TarifaAereo = 7.00m,
                            TarifaMaritimo = 4.00m,
                            Telefono = "88997711",
                            TipoCliente = "CONSUMIDOR_FINAL"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CodigoPais = "+505",
                            Direccion = "León, Parque Central 1c al norte",
                            Email = "leon@tienditaabba.com",
                            FechaRegistro = new DateTime(2026, 8, 14, 18, 22, 11, 902, DateTimeKind.Utc).AddTicks(5057),
                            Nombre = "Sucursal León (Mayorista B2B)",
                            TarifaAereo = 5.50m,
                            TarifaMaritimo = 3.00m,
                            Telefono = "87654321",
                            TipoCliente = "SUCURSAL_B2B"
                        });
                });

            modelBuilder.Entity("AbbaXpress.API.Models.GastoOperativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaGasto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("MontoUSD")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<decimal>("TipoCambioAplicado")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GastosOperativos");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("CostoProveedor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Label")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("PesoLbs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProformaId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalUSD")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TarifaAplicada")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tracking")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ViaEnvio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProformaId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Proforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CargoDeliveryUSD")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("DescuentoUSD")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("FechaFacturacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NumeroProforma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("SucursalDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("TipoCambioAplicado")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("TotalCobradoUSD")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalCostoProveedorUSD")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalLbs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SucursalDestinoId");

                    b.HasIndex("SucursalOrigenId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Proformas");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TipoSucursal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Ciudad = "Managua",
                            Direccion = "Bolonia, de Plaza España 1c al oeste",
                            FechaRegistro = new DateTime(2026, 8, 14, 18, 22, 11, 636, DateTimeKind.Utc).AddTicks(1252),
                            Nombre = "Sucursal Bolonia - Central",
                            Telefono = "+505 2222-1111",
                            TipoSucursal = "PROPIA"
                        },
                        new
                        {
                            Id = 2,
                            Activa = true,
                            Ciudad = "Managua",
                            Direccion = "Carretera Norte, Edificio Doral",
                            FechaRegistro = new DateTime(2026, 8, 14, 18, 22, 11, 636, DateTimeKind.Utc).AddTicks(1263),
                            Nombre = "Sucursal Doral",
                            Telefono = "+505 2222-2222",
                            TipoSucursal = "PROPIA"
                        },
                        new
                        {
                            Id = 3,
                            Activa = true,
                            Ciudad = "León",
                            Direccion = "Parque Central 1c al norte",
                            FechaRegistro = new DateTime(2026, 8, 14, 18, 22, 11, 636, DateTimeKind.Utc).AddTicks(1265),
                            Nombre = "Sucursal León",
                            Telefono = "+505 8765-4321",
                            TipoSucursal = "FRANQUICIA_B2B"
                        });
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 8, 14, 18, 22, 11, 636, DateTimeKind.Utc).AddTicks(1482),
                            Nombre = "Junior Ramírez (Super Admin)",
                            PasswordHash = "$2a$11$LPfmPl8A41qqziGcLgBK2ObzMwC8CJUf931ucD4cZfP3ap8nAEHhS",
                            Rol = "SUPER_ADMIN",
                            SucursalId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 8, 14, 18, 22, 11, 768, DateTimeKind.Utc).AddTicks(644),
                            Nombre = "Admin Sucursal León",
                            PasswordHash = "$2a$11$96grnGCLB5Ob3BEQfRyEWOmwQV1j5zCbj6VRWdXIiMGp9b2wXYfGa",
                            Rol = "ADMIN_SUCURSAL_INDEPENDIENTE",
                            SucursalId = 3,
                            Username = "adminleon"
                        });
                });

            modelBuilder.Entity("AbbaXpress.API.Models.GastoOperativo", b =>
                {
                    b.HasOne("AbbaXpress.API.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbbaXpress.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Paquete", b =>
                {
                    b.HasOne("AbbaXpress.API.Models.Proforma", "Proforma")
                        .WithMany("Paquetes")
                        .HasForeignKey("ProformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proforma");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Proforma", b =>
                {
                    b.HasOne("AbbaXpress.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbbaXpress.API.Models.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbbaXpress.API.Models.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("SucursalOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AbbaXpress.API.Models.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Usuario", b =>
                {
                    b.HasOne("AbbaXpress.API.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Proforma", b =>
                {
                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Sucursal", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
