// <auto-generated />
using System;
using AbbaXpress.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbbaXpress.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814181008_AddClientesModule")]
    partial class AddClientesModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AbbaXpress.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("TarifaAereo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TarifaMaritimo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CodigoPais = "+505",
                            Direccion = "Managua, Reparto San Juan",
                            Email = "juan.perez@email.com",
                            FechaRegistro = new DateTime(2026, 8, 14, 18, 10, 8, 23, DateTimeKind.Utc).AddTicks(8084),
                            Nombre = "Juan Carlos Pérez",
                            TarifaAereo = 7.00m,
                            TarifaMaritimo = 4.00m,
                            Telefono = "88997711",
                            TipoCliente = "CONSUMIDOR_FINAL"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CodigoPais = "+505",
                            Direccion = "León, Parque Central 1c al norte",
                            Email = "leon@tienditaabba.com",
                            FechaRegistro = new DateTime(2026, 8, 14, 18, 10, 8, 23, DateTimeKind.Utc).AddTicks(8173),
                            Nombre = "Sucursal León (Mayorista B2B)",
                            TarifaAereo = 5.50m,
                            TarifaMaritimo = 3.00m,
                            Telefono = "87654321",
                            TipoCliente = "SUCURSAL_B2B"
                        });
                });

            modelBuilder.Entity("AbbaXpress.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SucursalAsignada")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 8, 14, 18, 10, 7, 776, DateTimeKind.Utc).AddTicks(4115),
                            Nombre = "Junior Ramírez (Super Admin)",
                            PasswordHash = "$2a$11$Wwkn9Hx7/B.9W2LpntXedu2/GmFyVIda8176/qtBAhL5AuuRVfg2m",
                            Rol = "SUPER_ADMIN",
                            SucursalAsignada = "Sucursal Bolonia - Central",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 8, 14, 18, 10, 7, 899, DateTimeKind.Utc).AddTicks(2565),
                            Nombre = "Admin Sucursal León",
                            PasswordHash = "$2a$11$sIATnddbI5pjZbxlNl7Ufe/LfJxLfrjc6rgeNSfYy0BNMmamYC9RG",
                            Rol = "ADMIN_SUCURSAL_INDEPENDIENTE",
                            SucursalAsignada = "Sucursal León",
                            Username = "adminleon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
